export const typeIcons = {
  fire: require('../assets/types/fire-icon.png'),
  water: require('../assets/types/water-icon.png'),
  grass: require('../assets/types/grass-icon.png'),
  electric: require('../assets/types/electric-icon.png'),
  bug: require('../assets/types/bug-icon.png'),
  flying: require('../assets/types/flying-icon.png'),
  normal: require('../assets/types/normal-icon.png'),
  poison: require('../assets/types/poison-icon.png'),
  dark: require('../assets/types/dark-icon.png'),
  steel: require('../assets/types/steel-icon.png'),
  rock: require('../assets/types/rock-icon.png'),
  ground: require('../assets/types/ground-icon.png'),
  ghost: require('../assets/types/ghost-icon.png'),
  dragon: require('../assets/types/dragon-icon.png'),
  ice: require('../assets/types/ice-icon.png'),
  psychic: require('../assets/types/psychic-icon.png'),
  fighting: require('../assets/types/fighting-icon.png'),
  fairy: require('../assets/types/fairy-icon.png'),
};